version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/console/api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/console/web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"
