; Settings in these config files will be applied to every server in the battlegroup
; If you need to override different settings for different servers, use the battlegroup editor instead

[URL]
; The starting port that servers listen to for players. Each server
; will use the next available port in a sequence (7777, 7778 etc.). The range should
; not intersect with the IGWPort range bellow
Port=7777
; The port that servers listen to for other servers. Each server
; will use the next available port in a sequence (7888, 7889 etc.). The range should
; not intersect with the Port range above
IGWPort=7888

[ConsoleVariables]
; Set the name of every Sietch in the battlegroup
; If Sietches should have different names use the battlegroup editor instead
; Special characters like ' and | are not allowed and double quotes should be used
;Bgd.ServerDisplayName="My Arrakis, My Dune"

; Set a password for every Sietch in the battlegroup
; If Sietches should have different passwords use the battlegroup editor instead
; Special characters like ' and | are not allowed and double quotes should be used
;Bgd.ServerLoginPassword="Sandworm"

; Mining multipliers
Dune.GlobalMiningOutputMultiplier=1.0
Dune.GlobalVehicleMiningOutputMultiplier=1.0
SecurityZones.PvpResourceMultiplier=2.5

; Durability damage multiplier for vehicles | (0 to 10)  0=off
dw.VehicleDurabilityDamageMultiplier=1.0

; Sandstorm and sandstorm treasure spawning settings
Sandstorm.Enabled=1
Sandstorm.Treasure.Enabled=1 

; Sandworm settings
sandworm.dune.Enabled=1
; Sandworm can push/damage vehicles
Vehicle.SandwormCollisionInteraction=false
; Enables dangerzones where the sandworm can attack
Sandworm.SandwormDangerZonesEnabled=true
; Seconds of invunerability from sandworm on specific situations
Vehicle.SandwormInvulnerabilitySecondsOnExit=900.0
Vehicle.SandwormInvulnerabilitySecondsOnServerRestart=7200.0
