; Default UserGame values for dune-docker.
; When a map-specific UserGame override is created, it applies only to that map
; and replaces the baseline values from this file for that specific map.

[/Script/DuneSandbox.PvpPveSettings]
; Enable PVP for all partitions
m_bShouldForceEnablePvpOnAllPartitions=False
; Enable PVP for specific partitions. Example:
;+m_PvpEnabledPartitions=1
;+m_PvpEnabledPartitions=2

[/Script/DuneSandbox.SecurityZonesSubsystem]
; Disabling security zones across the board allows for PVP and ability usage everywhere
m_bAreSecurityZonesEnabled=True

[/DeteriorationSystem.ItemDeteriorationConstants]
; Deterioration rate for items | (0 to 10)  0=off
UpdateRateInSeconds=1.0

[/Script/DuneSandbox.SandStormConfig]
; Enable Coriolis storm
m_bCoriolisAutoSpawnEnabled=True

[/Script/DuneSandbox.BuildingSettings]
; Max number of landclaims. !Needs to also be applied to each client!
m_MaxNumLandclaimSegments=6
; Number of times a landclaim can be expanded
m_BuildingBlueprintMaxExtensions=4
m_BaseBackupMaxExtensions=8
; Enable building restriction limits !Needs to also be applied to each client!
m_bBuildingRestrictionLimitsEnabled=True
